const clolor_success = '#67C23A';
const clolor_warning = '#E6A23C';
const clolor_daner = '#F56C6C';
const clolor_info = '#E5EAF3';

const val_col_width = '90px';

// 模拟一些异步任务
const simulatedTask = async (ms, value) => {
  return new Promise(resolve => setTimeout(() => resolve(value), ms));
}

const style_cell = {
    header: {
        color:  '#0A0A0A',
        fontWeight: 'bold',
        backgroundColor: '#909399',
    },
    info: {
        color:  '#0A0A0A',
        fontWeight: 'normal',
        backgroundColor: clolor_info,
    },
    success: {
        color:  '#0A0A0A',
        fontWeight: 'normal',
        backgroundColor: clolor_success,
    },
    warning: {
        color:  '#0A0A0A',
        fontWeight: 'normal',
        backgroundColor: clolor_warning,
    },
    danger: {
        color:  '#0A0A0A',
        fontWeight: 'normal',
        backgroundColor: clolor_daner,
    },
}

const station = {
    name: 'abc PCBA test',
    id: '111123344',
    db: "abc_pcba.db",
    header: {
        description:{
            enable: true,
            label: 'Description',
            width: '200px',
            ...style_cell['header'],
        },
        lower:{
            enable: true,
            label: 'Lower',
            width: val_col_width,
            ...style_cell['header'],
        },
        upper:{
            enable: true,
            label: 'Upper',
            width: val_col_width,
            ...style_cell['header'],
        },
        unit:{
            enable: true,
            label: 'Unit',
            width: '50px',
            ...style_cell['header'],
        },
        slot1: {
            enable: true,
            label: 'Slot1',
            width: val_col_width,
            ...style_cell['header'],
        },
        slot2: {
            enable: true,
            label: 'Slot2',
            width: val_col_width,
            ...style_cell['header'],
        },
        slot3: {
            enable: true,
            label: 'Slot3',
            width: val_col_width,
            ...style_cell['header'],
        },
        slot4: {
            enable: false,
            label: 'Slot4',
            width: val_col_width,
            ...style_cell['header'],
        },
        slot5: {
            enable: true,
            label: 'Slot5',
            width: val_col_width,
            ...style_cell['header'],
        },
        slot6: {
            enable: true,
            label: 'Slot6',
            width: val_col_width,
            ...style_cell['header'],
        },
        slot7: {
            enable: true,
            label: 'Slot7',
            width: val_col_width,
            ...style_cell['header'],
        },
        slot8: {
            enable: true,
            label: 'Slot8',
            width: val_col_width,
            ...style_cell['header'],
        },
    },
    rows:[
        {
            id: 'u1111', //cuid(),
            text:{
                script: "console.log('Hello World I');",
                skiped: false,
                description: "这是第1行测试",
                lower: "123",
                upper: "456",
                unit: 'mm',
                slot1: "slot1.1",
                slot2: "slot2.1",
                slot3: "slot3.1",
                slot4: "slot4.1",
                slot5: "slot5.1",
                slot6: "slot6.1",
                slot7: "slot7.1",
                slot8: "slot8.1",
            },
            style: {
                description: style_cell['header'],
                lower: style_cell['header'],
                upper: style_cell['header'],
                unit: style_cell['header'],
                slot1: style_cell['info'],
                slot2: style_cell['info'],
                slot3: style_cell['info'],
                slot4: style_cell['info'],
                slot5: style_cell['info'],
                slot6: style_cell['info'],
                slot7: style_cell['info'],
                slot8: style_cell['info'],
            },
        },
        {
            id: 'u2222', //cuid(),
            text:{
                script: "console.log('Hello World II');",
                skiped: false,
                description: "这是第2行测试",
                lower: "123",
                upper: "456",
                unit: 'mm',
                slot1: "slot1.2",
                slot2: "slot2.2",
                slot3: "slot3.2",
                slot4: "slot4.2",
                slot5: "slot5.2",
                slot6: "slot6.2",
                slot7: "slot7.2",
                slot8: "slot8.2",
            },
            style: {
                description: style_cell['header'],
                lower: style_cell['header'],
                upper: style_cell['header'],
                unit: style_cell['header'],
                slot1: style_cell['info'],
                slot2: style_cell['info'],
                slot3: style_cell['info'],
                slot4: style_cell['info'],
                slot5: style_cell['info'],
                slot6: style_cell['info'],
                slot7: style_cell['info'],
                slot8: style_cell['info'],
            },
        },
        {
            id: 'u3333', //cuid(),
            text:{
                script: "console.log('Hello World II');",
                skiped: false,
                description: "这是第2行测试",
                lower: "123",
                upper: "456",
                unit: 'mm',
                slot1: "slot1.2",
                slot2: "slot2.2",
                slot3: "slot3.2",
                slot4: "slot4.2",
                slot5: "slot5.2",
                slot6: "slot6.2",
                slot7: "slot7.2",
                slot8: "slot8.2",
            },
            style: {
                description: style_cell['header'],
                lower: style_cell['header'],
                upper: style_cell['header'],
                unit: style_cell['header'],
                slot1: style_cell['info'],
                slot2: style_cell['info'],
                slot3: style_cell['info'],
                slot4: style_cell['info'],
                slot5: style_cell['info'],
                slot6: style_cell['info'],
                slot7: style_cell['info'],
                slot8: style_cell['info'],
            },
        },
        {
            id: 'u4444', //cuid(),
            text:{
                script: "console.log('Hello World II');",
                skiped: false,
                description: "这是第2行测试",
                lower: "123",
                upper: "456",
                unit: 'mm',
                slot1: "slot1.2",
                slot2: "slot2.2",
                slot3: "slot3.2",
                slot4: "slot4.2",
                slot5: "slot5.2",
                slot6: "slot6.2",
                slot7: "slot7.2",
                slot8: "slot8.2",
            },
            style: {
                description: style_cell['header'],
                lower: style_cell['header'],
                upper: style_cell['header'],
                unit: style_cell['header'],
                slot1: style_cell['info'],
                slot2: style_cell['info'],
                slot3: style_cell['info'],
                slot4: style_cell['info'],
                slot5: style_cell['info'],
                slot6: style_cell['info'],
                slot7: style_cell['info'],
                slot8: style_cell['info'],
            },
        },
        {
            id: 'u5555', //cuid(),
            text:{
                script: "console.log('Hello World II');",
                skiped: false,
                description: "这是第2行测试",
                lower: "123",
                upper: "456",
                unit: 'mm',
                slot1: "slot1.2",
                slot2: "slot2.2",
                slot3: "slot3.2",
                slot4: "slot4.2",
                slot5: "slot5.2",
                slot6: "slot6.2",
                slot7: "slot7.2",
                slot8: "slot8.2",
            },
            style: {
                description: style_cell['header'],
                lower: style_cell['header'],
                upper: style_cell['header'],
                unit: style_cell['header'],
                slot1: style_cell['info'],
                slot2: style_cell['info'],
                slot3: style_cell['info'],
                slot4: style_cell['info'],
                slot5: style_cell['info'],
                slot6: style_cell['info'],
                slot7: style_cell['info'],
                slot8: style_cell['info'],
            },
        },
        {
            id: 'u6666', //cuid(),
            text:{
                script: "console.log('Hello World II');",
                skiped: false,
                description: "这是第2行测试",
                lower: "123",
                upper: "456",
                unit: 'mm',
                slot1: "slot1.2",
                slot2: "slot2.2",
                slot3: "slot3.2",
                slot4: "slot4.2",
                slot5: "slot5.2",
                slot6: "slot6.2",
                slot7: "slot7.2",
                slot8: "slot8.2",
            },
            style: {
                description: style_cell['header'],
                lower: style_cell['header'],
                upper: style_cell['header'],
                unit: style_cell['header'],
                slot1: style_cell['info'],
                slot2: style_cell['info'],
                slot3: style_cell['info'],
                slot4: style_cell['info'],
                slot5: style_cell['info'],
                slot6: style_cell['info'],
                slot7: style_cell['info'],
                slot8: style_cell['info'],
            },
        },
        {
            id: 'u7777', //cuid(),
            text:{
                script: "console.log('Hello World II');",
                skiped: false,
                description: "这是第2行测试",
                lower: "123",
                upper: "456",
                unit: 'mm',
                slot1: "slot1.2",
                slot2: "slot2.2",
                slot3: "slot3.2",
                slot4: "slot4.2",
                slot5: "slot5.2",
                slot6: "slot6.2",
                slot7: "slot7.2",
                slot8: "slot8.2",
            },
            style: {
                description: style_cell['header'],
                lower: style_cell['header'],
                upper: style_cell['header'],
                unit: style_cell['header'],
                slot1: style_cell['info'],
                slot2: style_cell['info'],
                slot3: style_cell['info'],
                slot4: style_cell['info'],
                slot5: style_cell['info'],
                slot6: style_cell['info'],
                slot7: style_cell['info'],
                slot8: style_cell['info'],
            },
        },
        {
            id: 'u8888', //cuid(),
            text:{
                script: "console.log('Hello World II');",
                skiped: false,
                description: "这是第2行测试",
                lower: "123",
                upper: "456",
                unit: 'mm',
                slot1: "slot1.2",
                slot2: "slot2.2",
                slot3: "slot3.2",
                slot4: "slot4.2",
                slot5: "slot5.2",
                slot6: "slot6.2",
                slot7: "slot7.2",
                slot8: "slot8.2",
            },
            style: {
                description: style_cell['header'],
                lower: style_cell['header'],
                upper: style_cell['header'],
                unit: style_cell['header'],
                slot1: style_cell['info'],
                slot2: style_cell['info'],
                slot3: style_cell['info'],
                slot4: style_cell['info'],
                slot5: style_cell['info'],
                slot6: style_cell['info'],
                slot7: style_cell['info'],
                slot8: style_cell['info'],
            },
        },
        {
            id: 'u9999', //cuid(),
            text:{
                script: "console.log('Hello World II');",
                skiped: false,
                description: "这是第2行测试",
                lower: "123",
                upper: "456",
                unit: 'mm',
                slot1: "slot1.2",
                slot2: "slot2.2",
                slot3: "slot3.2",
                slot4: "slot4.2",
                slot5: "slot5.2",
                slot6: "slot6.2",
                slot7: "slot7.2",
                slot8: "slot8.2",
            },
            style: {
                description: style_cell['header'],
                lower: style_cell['header'],
                upper: style_cell['header'],
                unit: style_cell['header'],
                slot1: style_cell['info'],
                slot2: style_cell['info'],
                slot3: style_cell['info'],
                slot4: style_cell['info'],
                slot5: style_cell['info'],
                slot6: style_cell['info'],
                slot7: style_cell['info'],
                slot8: style_cell['info'],
            },
        },
        {
            id: 'uaaaa', //cuid(),
            text:{
                script: "console.log('Hello World II');",
                skiped: false,
                description: "这是第2行测试",
                lower: "123",
                upper: "456",
                unit: 'mm',
                slot1: "slot1.2",
                slot2: "slot2.2",
                slot3: "slot3.2",
                slot4: "slot4.2",
                slot5: "slot5.2",
                slot6: "slot6.2",
                slot7: "slot7.2",
                slot8: "slot8.2",
            },
            style: {
                description: style_cell['header'],
                lower: style_cell['header'],
                upper: style_cell['header'],
                unit: style_cell['header'],
                slot1: style_cell['info'],
                slot2: style_cell['info'],
                slot3: style_cell['info'],
                slot4: style_cell['info'],
                slot5: style_cell['info'],
                slot6: style_cell['info'],
                slot7: style_cell['info'],
                slot8: style_cell['info'],
            },
        }
    ],    
}


const items = {
    name: 'abc PCBA test',
    id: '111123344',
    db: "abc_pcba.db",
    slotEnables: {
        slot1: true,
        slot2: true,
        slot3: true,
        slot4: true,
        slot5: true,
        slot6: true,
        slot7: true,
        slot8: true,
    },
    rows:[
        {
            script: "console.log('Hello World I');",
            skiped: false,
            description: "这是第1行测试",
            lower: "123",
            upper: "456",
            unit: 'mm',
        },
        {
            script: "console.log('Hello World I');",
            skiped: false,
            description: "这是第1行测试",
            lower: "123",
            upper: "456",
            unit: 'mm',
        },
        {
            script: "console.log('Hello World II');",
            skiped: false,
            description: "这是第2行测试",
            lower: "123",
            upper: "456",
            unit: 'mm',
        },
        {
            script: "console.log('Hello World II');",
            skiped: false,
            description: "这是第2行测试",
            lower: "123",
            upper: "456",
            unit: 'mm',
        },
        {
            script: "console.log('Hello World II');",
            skiped: false,
            description: "这是第2行测试",
            lower: "123",
            upper: "456",
            unit: 'mm',
        },
        {
            script: "console.log('Hello World II');",
            skiped: false,
            description: "这是第2行测试",
            lower: "123",
            upper: "456",
            unit: 'mm',
        },
        {
            script: "console.log('Hello World II');",
            skiped: false,
            description: "这是第2行测试",
            lower: "123",
            upper: "456",
            unit: 'mm',
        },
        {
            script: "console.log('Hello World II');",
            skiped: false,
            description: "这是第2行测试",
            lower: "123",
            upper: "456",
            unit: 'mm',
        },
        {
            script: "console.log('Hello World II');",
            skiped: false,
            description: "这是第2行测试",
            lower: "123",
            upper: "456",
            unit: 'mm',
        },
        {
            script: "console.log('Hello World II');",
            skiped: false,
            description: "这是第2行测试",
            lower: "123",
            upper: "456",
            unit: 'mm',
        },
        {
            script: "console.log('Hello World II');",
            skiped: false,
            description: "这是第2行测试",
            lower: "123",
            upper: "456",
            unit: 'mm',
        }
    ],    
}




export {
    clolor_success,
    clolor_warning,
    clolor_daner,
    clolor_info,
    style_cell,
    station,
}


